
(function(){var initializing=false,fnTest=/xyz/.test(function(){xyz;})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(prop){var _super=this.prototype;initializing=true;var prototype=new this();initializing=false;for(var name in prop){prototype[name]=typeof prop[name]=="function"&&typeof _super[name]=="function"&&fnTest.test(prop[name])?(function(name,fn){return function(){var tmp=this._super;this._super=_super[name];var ret=fn.apply(this,arguments);this._super=tmp;return ret;};})(name,prop[name]):prop[name];}
function Class(){if(!initializing&&this.init)
this.init.apply(this,arguments);}
Class.prototype=prototype;Class.constructor=Class;Class.extend=arguments.callee;return Class;};var Project=Class.extend({init:function(name,date){this.name=name;this.createDate=date;this.bugs=[];},name:null,createDate:null,bugs:null,add:function(bug){this.bugs.push(bug);},remove:function(index){this.bugs.splice(index,1);}});var Bug=Class.extend({init:function(id,description,bugDate,bugStatus){this.id=id;this.description=description;this.bugDate=bugDate;this.bugStatus=bugStatus;this.comments=[];},id:null,description:null,bugDate:null,bugStatus:null,comments:null,add:function(comment){this.comments.push(comment);},remove:function(index){this.comments.splice(index,1);}});var Status=Class.extend({init:function(name,color){this.name=name;this.color=color;},name:null,color:null});var Comment=Class.extend({init:function(text,date){this.commentText=text;this.commentDate=date;},commentText:null,commentDate:null});var BugTrackr={projectArray:[],statusArray:[],Project:Project,Bug:Bug,Status:Status,Comment:Comment,dom:{wrapper:"wrapper",projectsWrapper:"projectsWrapper",projectForm:"projectForm",createProjectButton:"projectButton",projectsDiv:"projectsDiv",projectDiv:"project",bugText:"bugText",bugWrapper:"bugWrapper",createBug:"createBug",projectBugs:"projectBugs",statusSelect:"statusSelect",projectText:"projectText",singleProjectWrapper:"singleProjectWrapper",bugCommentsHref:"bugCommentsHref",bugEdit:"bugEdit",bugDelete:"bugDelete",bugComments:"bugComments",bugSave:"bugSave",commentText:"commentText",statusBug:"statusBug",bugDesc:"bugDesc",sendComment:"sendComment"},init:function()
{paper=new Raphael(document.getElementById('splashScreen'),700,700);var t=paper.text((700/2),100,"BugTrackr");t.attr({fill:'#000','font-size':44});var p=paper.path("M10 150 L10 150");p.attr({stroke:'#000','stroke-width':7});p.animate({path:"M 20 150 L680 150"},3000);var i=paper.image("img/bug.png",(700/2-(128/2)),700,128,128);i.animate({y:700/2-128/2},3000,'bounce',function(){$('#splashScreen').animate({opacity:0},500,function(){$('#splashScreen').remove();});});BugTrackr.createStatuses();var p=new Project("BugTrackr",this.getDateString());var b1=new Bug("#0","This is an imaginary bug, that is probably very hard to solve.",this.getDateString(),this.statusArray[0]);p.add(b1);var c1=new Comment("We need to check this out before version 1.0.1",this.getDateString());b1.add(c1);var b3=new Bug("#1","Show recently created project and set first project to active on startup",this.getDateString(),this.statusArray[3]);p.add(b3);var p2=new Project("Skilroy",this.getDateString());var p3=new Project("Exjobb",this.getDateString());var p4=new Project("iPhone app",this.getDateString());$("#"+this.dom.createProjectButton).bind("click",function(){BugTrackr.createProject();return false;});BugTrackr.checkForProjects();if(this.projectArray.length>0)
{this.showProject(0);window.location.hash="project0s"}
this.setup();},setup:function()
{$(window).bind('hashchange',function(){var hash=location.hash;$("#"+BugTrackr.dom.projectsDiv+" a").each(function(index){if(hash!=="")
{var that=$(this);if(that.attr('href')+"s"===hash)
{that.parent().addClass('ui-state-active');BugTrackr.showProject(index);}
else
{that.parent().removeClass('ui-state-active');}}});})
$(window).trigger('hashchange');},checkForProjects:function()
{var projectsDiv=$("#"+this.dom.projectsDiv);projectsDiv.text("");$.each(this.projectArray,function(intIndex,p)
{projectsDiv.append("<div class='project ui-state-default'><a href='#project"+intIndex+"' id='"+BugTrackr.dom.projectDiv+intIndex+"'>"+p.name+"</a></div>");var tempDiv=$("#"+BugTrackr.dom.projectDiv+intIndex);tempDiv.bind("click",function(){window.location.hash=tempDiv.attr("id")+"s";return false;});tempDiv.mouseover(function(){tempDiv.parent().addClass("ui-state-hover");}).mouseout(function(){tempDiv.parent().removeClass("ui-state-hover");});});},createProject:function()
{var projectTextField=$("#"+this.dom.projectText);var projectName=projectTextField.val();var newProject=new Project(projectName,this.getDateString());this.projectArray.push(newProject);this.checkForProjects();projectTextField.val("");this.showProject(this.projectArray.length-1);window.location.hash="project"+(this.projectArray.length-1)+"s";},showProject:function(index)
{var project=this.projectArray[index];var sProjectWrapper=$("#"+this.dom.singleProjectWrapper);sProjectWrapper.text("");sProjectWrapper.append("<h1>"+project.name+"</h1>");sProjectWrapper.append("<textarea id='"+this.dom.bugText+"' rows='5' class='bugTextField' />");sProjectWrapper.append("<select name='bugStatuses' id='"+this.dom.statusSelect+"'></select>");$.each(this.statusArray,function(intIndex,s)
{$("#"+BugTrackr.dom.statusSelect).append("<option value='"+intIndex+"'>"+s.name+"</option>");});sProjectWrapper.append("<input type='submit' id='"+this.dom.createBug+"' class='createBugButton ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' value='Create bug' />");sProjectWrapper.append("<div class='clear'></div>");sProjectWrapper.append("<div id='"+this.dom.projectBugs+"'></div>");$("#"+this.dom.createBug).bind("click",function(){BugTrackr.createBug(project);return false;});BugTrackr.getProjectBugs(project);},createStatuses:function()
{if(this.statusArray.length===0)
{var s1=new Status("New","#FFA0A0");this.statusArray.push(s1);var s2=new Status("Feedback","#FF50A8");this.statusArray.push(s2);var s3=new Status("Acknowledged","#FFD850");this.statusArray.push(s3);var s4=new Status("Confirmed","#FFFFB0");this.statusArray.push(s4);var s5=new Status("Assigned","#C8C8FF");this.statusArray.push(s5);var s6=new Status("Resolved","#CCEEDD");this.statusArray.push(s6);var s7=new Status("Closed","#E8E8E8");this.statusArray.push(s7);}},getProjectBugs:function(project)
{var projectBugsNode=$("#"+this.dom.projectBugs);projectBugsNode.text("");$.each(project.bugs,function(intIndex,b)
{projectBugsNode.append("<div id='"+BugTrackr.dom.bugWrapper+intIndex+"' class='singleBug'></div>");var bugWrapper=$("#"+BugTrackr.dom.bugWrapper+intIndex);bugWrapper.append(b.bugDate+" - Status: "+b.bugStatus.name);bugWrapper.append("<div class='statusColor' style='background-color: "+b.bugStatus.color+";'></div><br />")
bugWrapper.append("<p>"+b.description+"</p>");bugWrapper.append("<a href='#' id='"+BugTrackr.dom.bugCommentsHref+intIndex+"'>Comments ("+b.comments.length+")</a> - ");bugWrapper.append("<a href='#' id='"+BugTrackr.dom.bugEdit+intIndex+"'>Edit</a> - ");bugWrapper.append("<a href='#' id='"+BugTrackr.dom.bugDelete+intIndex+"'>Delete</a>");bugWrapper.append("<div id='"+BugTrackr.dom.bugComments+intIndex+"' class='comments'></div>");var bugComments=$("#"+BugTrackr.dom.bugComments+intIndex);$.each(b.comments,function(intIndex,c)
{bugComments.append("<p>"+c.commentText+"<br />"+c.commentDate+"</p>");});bugComments.append("<textarea id='"+BugTrackr.dom.commentText+intIndex+"' rows='3' class='commentTextField' /><br />");bugComments.append("<input type='submit' id='"+BugTrackr.dom.sendComment+intIndex+"' value='Send' class='commentButton ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' />");bugComments.append("<div class='clear'></div>");bugComments.hide();bugWrapper.addClass("ui-corner-all");bugWrapper.css("background-color","#E6E6E6");$("#"+BugTrackr.dom.bugCommentsHref+intIndex).bind("click",function(){BugTrackr.toggleComment(intIndex);});$("#"+BugTrackr.dom.bugEdit+intIndex).bind("click",function(){BugTrackr.editBug(project,intIndex);});$("#"+BugTrackr.dom.bugDelete+intIndex).bind("click",function(){BugTrackr.deleteBug(project,intIndex);});$("#"+BugTrackr.dom.sendComment+intIndex+"").bind("click",function(){BugTrackr.createComment(project,intIndex);return false;});});},createBug:function(project)
{var bugText=$("#"+this.dom.bugText);var bugStatus=this.statusArray[$("#"+this.dom.statusSelect).val()];var bug=new Bug(project.bugs.length,bugText.val(),this.getDateString(),bugStatus);project.add(bug);BugTrackr.getProjectBugs(project);bugText.val("");},editBug:function(project,bugIndex)
{var b=project.bugs[bugIndex];var bugWrapper=$("#"+this.dom.bugWrapper+bugIndex);bugWrapper.empty();bugWrapper.append(b.bugDate+" - Status: ");bugWrapper.append("<select name='bugStatuses' id='"+this.dom.statusBug+bugIndex+"'></select>");$.each(this.statusArray,function(intIndex,s)
{$("#"+BugTrackr.dom.statusBug+bugIndex+"").append("<option value='"+intIndex+"'>"+s.name+"</option>");});$.each(this.statusArray,function(intIndex,s)
{if(s===b.bugStatus)
{$("#"+BugTrackr.dom.statusBug+bugIndex+" option[value='"+intIndex+"']").attr('selected','selected');}});bugWrapper.append("<div class='statusColor' style='background-color: "+b.bugStatus.color+";'></div><br />")
bugWrapper.append("<textarea id='"+this.dom.bugDesc+bugIndex+"' rows='3' class='editBugTextField'>"+b.description+"</textarea><br />");bugWrapper.append("<a href='#' id='"+this.dom.bugCommentsHref+bugIndex+"'>Comments ("+b.comments.length+")</a> - ");bugWrapper.append("<a href='#' id='"+this.dom.bugSave+bugIndex+"'>Save</a> - ");bugWrapper.append("<a href='#' id='"+this.dom.bugDelete+bugIndex+"'>Delete</a>");bugWrapper.append("<div id='"+this.dom.bugComments+bugIndex+"' class='comments'></div>");var bugComments=$("#"+BugTrackr.dom.bugComments+bugIndex);$.each(b.comments,function(intIndex,c)
{bugComments.append("<p>"+c.commentText+"<br />"+c.commentDate+"</p>");});bugComments.append("<textarea id='"+this.dom.commentText+bugIndex+"' rows='3' class='commentTextField' /><br />");bugComments.append("<input type='submit' id='"+this.dom.sendComment+bugIndex+"' class='commentButton ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' value='Send' />");bugComments.append("<div class='clear'></div>");bugComments.hide();$("#bugCommentsHref"+bugIndex).bind("click",function(){BugTrackr.toggleComment(bugIndex);});$("#bugSave"+bugIndex).bind("click",function(){BugTrackr.saveBug(project,bugIndex);});$("#bugDelete"+bugIndex).bind("click",function(){BugTrackr.deleteBug(project,bugIndex);});$("#sendComment"+bugIndex).bind("click",function(){BugTrackr.createComment(project,bugIndex);return false;});},saveBug:function(project,bugIndex)
{var bug=project.bugs[bugIndex];var bugStatus=this.statusArray[$("#"+this.dom.statusBug+bugIndex+"").val()];bug.description=$("#"+this.dom.bugDesc+bugIndex).val();bug.bugStatus=bugStatus;BugTrackr.getProjectBugs(project);},deleteBug:function(project,bugIndex)
{project.bugs.splice(bugIndex,1);BugTrackr.getProjectBugs(project);},createComment:function(project,index)
{var bug=project.bugs[index];var comment=new Comment($("#"+this.dom.commentText+index+"").val(),BugTrackr.getDateString());bug.add(comment);BugTrackr.getProjectBugs(project);},toggleComment:function(index)
{$("#"+this.dom.bugComments+index).slideToggle("slow");},getDateString:function()
{var date=new Date();var year=date.getFullYear();var month=date.getMonth()+1;if(month<10){month="0"+month;}
var day=date.getDate();var hour=date.getHours();if(hour<10){hour="0"+hour;}
var minutes=date.getMinutes();if(minutes<10){minutes="0"+minutes;}
var dateStr=year+"-"+month+"-"+day+" "+hour+":"+minutes;return dateStr;},data:{}};BugTrackr.init();window.BugTrackr=BugTrackr;})();